# Generated by Django 2.1.5 on 2019-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=30)),
            ],
        ),
    ]
